package com.oo.test.model.ly;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class LyRuleResultExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_ly_rule_result
     *
     * @mbggenerated Mon Jun 12 16:25:49 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_ly_rule_result
     *
     * @mbggenerated Mon Jun 12 16:25:49 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_ly_rule_result
     *
     * @mbggenerated Mon Jun 12 16:25:49 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ly_rule_result
     *
     * @mbggenerated Mon Jun 12 16:25:49 CST 2017
     */
    public LyRuleResultExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ly_rule_result
     *
     * @mbggenerated Mon Jun 12 16:25:49 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ly_rule_result
     *
     * @mbggenerated Mon Jun 12 16:25:49 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ly_rule_result
     *
     * @mbggenerated Mon Jun 12 16:25:49 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ly_rule_result
     *
     * @mbggenerated Mon Jun 12 16:25:49 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ly_rule_result
     *
     * @mbggenerated Mon Jun 12 16:25:49 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ly_rule_result
     *
     * @mbggenerated Mon Jun 12 16:25:49 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ly_rule_result
     *
     * @mbggenerated Mon Jun 12 16:25:49 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ly_rule_result
     *
     * @mbggenerated Mon Jun 12 16:25:49 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ly_rule_result
     *
     * @mbggenerated Mon Jun 12 16:25:49 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ly_rule_result
     *
     * @mbggenerated Mon Jun 12 16:25:49 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_ly_rule_result
     *
     * @mbggenerated Mon Jun 12 16:25:49 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andAppCodeIsNull() {
            addCriterion("app_code is null");
            return (Criteria) this;
        }

        public Criteria andAppCodeIsNotNull() {
            addCriterion("app_code is not null");
            return (Criteria) this;
        }

        public Criteria andAppCodeEqualTo(String value) {
            addCriterion("app_code =", value, "appCode");
            return (Criteria) this;
        }

        public Criteria andAppCodeNotEqualTo(String value) {
            addCriterion("app_code <>", value, "appCode");
            return (Criteria) this;
        }

        public Criteria andAppCodeGreaterThan(String value) {
            addCriterion("app_code >", value, "appCode");
            return (Criteria) this;
        }

        public Criteria andAppCodeGreaterThanOrEqualTo(String value) {
            addCriterion("app_code >=", value, "appCode");
            return (Criteria) this;
        }

        public Criteria andAppCodeLessThan(String value) {
            addCriterion("app_code <", value, "appCode");
            return (Criteria) this;
        }

        public Criteria andAppCodeLessThanOrEqualTo(String value) {
            addCriterion("app_code <=", value, "appCode");
            return (Criteria) this;
        }

        public Criteria andAppCodeLike(String value) {
            addCriterion("app_code like", value, "appCode");
            return (Criteria) this;
        }

        public Criteria andAppCodeNotLike(String value) {
            addCriterion("app_code not like", value, "appCode");
            return (Criteria) this;
        }

        public Criteria andAppCodeIn(List<String> values) {
            addCriterion("app_code in", values, "appCode");
            return (Criteria) this;
        }

        public Criteria andAppCodeNotIn(List<String> values) {
            addCriterion("app_code not in", values, "appCode");
            return (Criteria) this;
        }

        public Criteria andAppCodeBetween(String value1, String value2) {
            addCriterion("app_code between", value1, value2, "appCode");
            return (Criteria) this;
        }

        public Criteria andAppCodeNotBetween(String value1, String value2) {
            addCriterion("app_code not between", value1, value2, "appCode");
            return (Criteria) this;
        }

        public Criteria andBeforeResultIsNull() {
            addCriterion("before_result is null");
            return (Criteria) this;
        }

        public Criteria andBeforeResultIsNotNull() {
            addCriterion("before_result is not null");
            return (Criteria) this;
        }

        public Criteria andBeforeResultEqualTo(String value) {
            addCriterion("before_result =", value, "beforeResult");
            return (Criteria) this;
        }

        public Criteria andBeforeResultNotEqualTo(String value) {
            addCriterion("before_result <>", value, "beforeResult");
            return (Criteria) this;
        }

        public Criteria andBeforeResultGreaterThan(String value) {
            addCriterion("before_result >", value, "beforeResult");
            return (Criteria) this;
        }

        public Criteria andBeforeResultGreaterThanOrEqualTo(String value) {
            addCriterion("before_result >=", value, "beforeResult");
            return (Criteria) this;
        }

        public Criteria andBeforeResultLessThan(String value) {
            addCriterion("before_result <", value, "beforeResult");
            return (Criteria) this;
        }

        public Criteria andBeforeResultLessThanOrEqualTo(String value) {
            addCriterion("before_result <=", value, "beforeResult");
            return (Criteria) this;
        }

        public Criteria andBeforeResultLike(String value) {
            addCriterion("before_result like", value, "beforeResult");
            return (Criteria) this;
        }

        public Criteria andBeforeResultNotLike(String value) {
            addCriterion("before_result not like", value, "beforeResult");
            return (Criteria) this;
        }

        public Criteria andBeforeResultIn(List<String> values) {
            addCriterion("before_result in", values, "beforeResult");
            return (Criteria) this;
        }

        public Criteria andBeforeResultNotIn(List<String> values) {
            addCriterion("before_result not in", values, "beforeResult");
            return (Criteria) this;
        }

        public Criteria andBeforeResultBetween(String value1, String value2) {
            addCriterion("before_result between", value1, value2, "beforeResult");
            return (Criteria) this;
        }

        public Criteria andBeforeResultNotBetween(String value1, String value2) {
            addCriterion("before_result not between", value1, value2, "beforeResult");
            return (Criteria) this;
        }

        public Criteria andAfterResultIsNull() {
            addCriterion("after_result is null");
            return (Criteria) this;
        }

        public Criteria andAfterResultIsNotNull() {
            addCriterion("after_result is not null");
            return (Criteria) this;
        }

        public Criteria andAfterResultEqualTo(String value) {
            addCriterion("after_result =", value, "afterResult");
            return (Criteria) this;
        }

        public Criteria andAfterResultNotEqualTo(String value) {
            addCriterion("after_result <>", value, "afterResult");
            return (Criteria) this;
        }

        public Criteria andAfterResultGreaterThan(String value) {
            addCriterion("after_result >", value, "afterResult");
            return (Criteria) this;
        }

        public Criteria andAfterResultGreaterThanOrEqualTo(String value) {
            addCriterion("after_result >=", value, "afterResult");
            return (Criteria) this;
        }

        public Criteria andAfterResultLessThan(String value) {
            addCriterion("after_result <", value, "afterResult");
            return (Criteria) this;
        }

        public Criteria andAfterResultLessThanOrEqualTo(String value) {
            addCriterion("after_result <=", value, "afterResult");
            return (Criteria) this;
        }

        public Criteria andAfterResultLike(String value) {
            addCriterion("after_result like", value, "afterResult");
            return (Criteria) this;
        }

        public Criteria andAfterResultNotLike(String value) {
            addCriterion("after_result not like", value, "afterResult");
            return (Criteria) this;
        }

        public Criteria andAfterResultIn(List<String> values) {
            addCriterion("after_result in", values, "afterResult");
            return (Criteria) this;
        }

        public Criteria andAfterResultNotIn(List<String> values) {
            addCriterion("after_result not in", values, "afterResult");
            return (Criteria) this;
        }

        public Criteria andAfterResultBetween(String value1, String value2) {
            addCriterion("after_result between", value1, value2, "afterResult");
            return (Criteria) this;
        }

        public Criteria andAfterResultNotBetween(String value1, String value2) {
            addCriterion("after_result not between", value1, value2, "afterResult");
            return (Criteria) this;
        }

        public Criteria andWorkflowQueueIsNull() {
            addCriterion("workflow_queue is null");
            return (Criteria) this;
        }

        public Criteria andWorkflowQueueIsNotNull() {
            addCriterion("workflow_queue is not null");
            return (Criteria) this;
        }

        public Criteria andWorkflowQueueEqualTo(String value) {
            addCriterion("workflow_queue =", value, "workflowQueue");
            return (Criteria) this;
        }

        public Criteria andWorkflowQueueNotEqualTo(String value) {
            addCriterion("workflow_queue <>", value, "workflowQueue");
            return (Criteria) this;
        }

        public Criteria andWorkflowQueueGreaterThan(String value) {
            addCriterion("workflow_queue >", value, "workflowQueue");
            return (Criteria) this;
        }

        public Criteria andWorkflowQueueGreaterThanOrEqualTo(String value) {
            addCriterion("workflow_queue >=", value, "workflowQueue");
            return (Criteria) this;
        }

        public Criteria andWorkflowQueueLessThan(String value) {
            addCriterion("workflow_queue <", value, "workflowQueue");
            return (Criteria) this;
        }

        public Criteria andWorkflowQueueLessThanOrEqualTo(String value) {
            addCriterion("workflow_queue <=", value, "workflowQueue");
            return (Criteria) this;
        }

        public Criteria andWorkflowQueueLike(String value) {
            addCriterion("workflow_queue like", value, "workflowQueue");
            return (Criteria) this;
        }

        public Criteria andWorkflowQueueNotLike(String value) {
            addCriterion("workflow_queue not like", value, "workflowQueue");
            return (Criteria) this;
        }

        public Criteria andWorkflowQueueIn(List<String> values) {
            addCriterion("workflow_queue in", values, "workflowQueue");
            return (Criteria) this;
        }

        public Criteria andWorkflowQueueNotIn(List<String> values) {
            addCriterion("workflow_queue not in", values, "workflowQueue");
            return (Criteria) this;
        }

        public Criteria andWorkflowQueueBetween(String value1, String value2) {
            addCriterion("workflow_queue between", value1, value2, "workflowQueue");
            return (Criteria) this;
        }

        public Criteria andWorkflowQueueNotBetween(String value1, String value2) {
            addCriterion("workflow_queue not between", value1, value2, "workflowQueue");
            return (Criteria) this;
        }

        public Criteria andStragetyversionIsNull() {
            addCriterion("stragetyversion is null");
            return (Criteria) this;
        }

        public Criteria andStragetyversionIsNotNull() {
            addCriterion("stragetyversion is not null");
            return (Criteria) this;
        }

        public Criteria andStragetyversionEqualTo(String value) {
            addCriterion("stragetyversion =", value, "stragetyversion");
            return (Criteria) this;
        }

        public Criteria andStragetyversionNotEqualTo(String value) {
            addCriterion("stragetyversion <>", value, "stragetyversion");
            return (Criteria) this;
        }

        public Criteria andStragetyversionGreaterThan(String value) {
            addCriterion("stragetyversion >", value, "stragetyversion");
            return (Criteria) this;
        }

        public Criteria andStragetyversionGreaterThanOrEqualTo(String value) {
            addCriterion("stragetyversion >=", value, "stragetyversion");
            return (Criteria) this;
        }

        public Criteria andStragetyversionLessThan(String value) {
            addCriterion("stragetyversion <", value, "stragetyversion");
            return (Criteria) this;
        }

        public Criteria andStragetyversionLessThanOrEqualTo(String value) {
            addCriterion("stragetyversion <=", value, "stragetyversion");
            return (Criteria) this;
        }

        public Criteria andStragetyversionLike(String value) {
            addCriterion("stragetyversion like", value, "stragetyversion");
            return (Criteria) this;
        }

        public Criteria andStragetyversionNotLike(String value) {
            addCriterion("stragetyversion not like", value, "stragetyversion");
            return (Criteria) this;
        }

        public Criteria andStragetyversionIn(List<String> values) {
            addCriterion("stragetyversion in", values, "stragetyversion");
            return (Criteria) this;
        }

        public Criteria andStragetyversionNotIn(List<String> values) {
            addCriterion("stragetyversion not in", values, "stragetyversion");
            return (Criteria) this;
        }

        public Criteria andStragetyversionBetween(String value1, String value2) {
            addCriterion("stragetyversion between", value1, value2, "stragetyversion");
            return (Criteria) this;
        }

        public Criteria andStragetyversionNotBetween(String value1, String value2) {
            addCriterion("stragetyversion not between", value1, value2, "stragetyversion");
            return (Criteria) this;
        }

        public Criteria andStragetyversionDateIsNull() {
            addCriterion("stragetyversion_date is null");
            return (Criteria) this;
        }

        public Criteria andStragetyversionDateIsNotNull() {
            addCriterion("stragetyversion_date is not null");
            return (Criteria) this;
        }

        public Criteria andStragetyversionDateEqualTo(String value) {
            addCriterion("stragetyversion_date =", value, "stragetyversionDate");
            return (Criteria) this;
        }

        public Criteria andStragetyversionDateNotEqualTo(String value) {
            addCriterion("stragetyversion_date <>", value, "stragetyversionDate");
            return (Criteria) this;
        }

        public Criteria andStragetyversionDateGreaterThan(String value) {
            addCriterion("stragetyversion_date >", value, "stragetyversionDate");
            return (Criteria) this;
        }

        public Criteria andStragetyversionDateGreaterThanOrEqualTo(String value) {
            addCriterion("stragetyversion_date >=", value, "stragetyversionDate");
            return (Criteria) this;
        }

        public Criteria andStragetyversionDateLessThan(String value) {
            addCriterion("stragetyversion_date <", value, "stragetyversionDate");
            return (Criteria) this;
        }

        public Criteria andStragetyversionDateLessThanOrEqualTo(String value) {
            addCriterion("stragetyversion_date <=", value, "stragetyversionDate");
            return (Criteria) this;
        }

        public Criteria andStragetyversionDateLike(String value) {
            addCriterion("stragetyversion_date like", value, "stragetyversionDate");
            return (Criteria) this;
        }

        public Criteria andStragetyversionDateNotLike(String value) {
            addCriterion("stragetyversion_date not like", value, "stragetyversionDate");
            return (Criteria) this;
        }

        public Criteria andStragetyversionDateIn(List<String> values) {
            addCriterion("stragetyversion_date in", values, "stragetyversionDate");
            return (Criteria) this;
        }

        public Criteria andStragetyversionDateNotIn(List<String> values) {
            addCriterion("stragetyversion_date not in", values, "stragetyversionDate");
            return (Criteria) this;
        }

        public Criteria andStragetyversionDateBetween(String value1, String value2) {
            addCriterion("stragetyversion_date between", value1, value2, "stragetyversionDate");
            return (Criteria) this;
        }

        public Criteria andStragetyversionDateNotBetween(String value1, String value2) {
            addCriterion("stragetyversion_date not between", value1, value2, "stragetyversionDate");
            return (Criteria) this;
        }

        public Criteria andZhengxinAbnormalIsNull() {
            addCriterion("zhengxin_abnormal is null");
            return (Criteria) this;
        }

        public Criteria andZhengxinAbnormalIsNotNull() {
            addCriterion("zhengxin_abnormal is not null");
            return (Criteria) this;
        }

        public Criteria andZhengxinAbnormalEqualTo(String value) {
            addCriterion("zhengxin_abnormal =", value, "zhengxinAbnormal");
            return (Criteria) this;
        }

        public Criteria andZhengxinAbnormalNotEqualTo(String value) {
            addCriterion("zhengxin_abnormal <>", value, "zhengxinAbnormal");
            return (Criteria) this;
        }

        public Criteria andZhengxinAbnormalGreaterThan(String value) {
            addCriterion("zhengxin_abnormal >", value, "zhengxinAbnormal");
            return (Criteria) this;
        }

        public Criteria andZhengxinAbnormalGreaterThanOrEqualTo(String value) {
            addCriterion("zhengxin_abnormal >=", value, "zhengxinAbnormal");
            return (Criteria) this;
        }

        public Criteria andZhengxinAbnormalLessThan(String value) {
            addCriterion("zhengxin_abnormal <", value, "zhengxinAbnormal");
            return (Criteria) this;
        }

        public Criteria andZhengxinAbnormalLessThanOrEqualTo(String value) {
            addCriterion("zhengxin_abnormal <=", value, "zhengxinAbnormal");
            return (Criteria) this;
        }

        public Criteria andZhengxinAbnormalLike(String value) {
            addCriterion("zhengxin_abnormal like", value, "zhengxinAbnormal");
            return (Criteria) this;
        }

        public Criteria andZhengxinAbnormalNotLike(String value) {
            addCriterion("zhengxin_abnormal not like", value, "zhengxinAbnormal");
            return (Criteria) this;
        }

        public Criteria andZhengxinAbnormalIn(List<String> values) {
            addCriterion("zhengxin_abnormal in", values, "zhengxinAbnormal");
            return (Criteria) this;
        }

        public Criteria andZhengxinAbnormalNotIn(List<String> values) {
            addCriterion("zhengxin_abnormal not in", values, "zhengxinAbnormal");
            return (Criteria) this;
        }

        public Criteria andZhengxinAbnormalBetween(String value1, String value2) {
            addCriterion("zhengxin_abnormal between", value1, value2, "zhengxinAbnormal");
            return (Criteria) this;
        }

        public Criteria andZhengxinAbnormalNotBetween(String value1, String value2) {
            addCriterion("zhengxin_abnormal not between", value1, value2, "zhengxinAbnormal");
            return (Criteria) this;
        }

        public Criteria andTestFlagIsNull() {
            addCriterion("test_flag is null");
            return (Criteria) this;
        }

        public Criteria andTestFlagIsNotNull() {
            addCriterion("test_flag is not null");
            return (Criteria) this;
        }

        public Criteria andTestFlagEqualTo(String value) {
            addCriterion("test_flag =", value, "testFlag");
            return (Criteria) this;
        }

        public Criteria andTestFlagNotEqualTo(String value) {
            addCriterion("test_flag <>", value, "testFlag");
            return (Criteria) this;
        }

        public Criteria andTestFlagGreaterThan(String value) {
            addCriterion("test_flag >", value, "testFlag");
            return (Criteria) this;
        }

        public Criteria andTestFlagGreaterThanOrEqualTo(String value) {
            addCriterion("test_flag >=", value, "testFlag");
            return (Criteria) this;
        }

        public Criteria andTestFlagLessThan(String value) {
            addCriterion("test_flag <", value, "testFlag");
            return (Criteria) this;
        }

        public Criteria andTestFlagLessThanOrEqualTo(String value) {
            addCriterion("test_flag <=", value, "testFlag");
            return (Criteria) this;
        }

        public Criteria andTestFlagLike(String value) {
            addCriterion("test_flag like", value, "testFlag");
            return (Criteria) this;
        }

        public Criteria andTestFlagNotLike(String value) {
            addCriterion("test_flag not like", value, "testFlag");
            return (Criteria) this;
        }

        public Criteria andTestFlagIn(List<String> values) {
            addCriterion("test_flag in", values, "testFlag");
            return (Criteria) this;
        }

        public Criteria andTestFlagNotIn(List<String> values) {
            addCriterion("test_flag not in", values, "testFlag");
            return (Criteria) this;
        }

        public Criteria andTestFlagBetween(String value1, String value2) {
            addCriterion("test_flag between", value1, value2, "testFlag");
            return (Criteria) this;
        }

        public Criteria andTestFlagNotBetween(String value1, String value2) {
            addCriterion("test_flag not between", value1, value2, "testFlag");
            return (Criteria) this;
        }

        public Criteria andMergeRcodeIsNull() {
            addCriterion("merge_rcode is null");
            return (Criteria) this;
        }

        public Criteria andMergeRcodeIsNotNull() {
            addCriterion("merge_rcode is not null");
            return (Criteria) this;
        }

        public Criteria andMergeRcodeEqualTo(String value) {
            addCriterion("merge_rcode =", value, "mergeRcode");
            return (Criteria) this;
        }

        public Criteria andMergeRcodeNotEqualTo(String value) {
            addCriterion("merge_rcode <>", value, "mergeRcode");
            return (Criteria) this;
        }

        public Criteria andMergeRcodeGreaterThan(String value) {
            addCriterion("merge_rcode >", value, "mergeRcode");
            return (Criteria) this;
        }

        public Criteria andMergeRcodeGreaterThanOrEqualTo(String value) {
            addCriterion("merge_rcode >=", value, "mergeRcode");
            return (Criteria) this;
        }

        public Criteria andMergeRcodeLessThan(String value) {
            addCriterion("merge_rcode <", value, "mergeRcode");
            return (Criteria) this;
        }

        public Criteria andMergeRcodeLessThanOrEqualTo(String value) {
            addCriterion("merge_rcode <=", value, "mergeRcode");
            return (Criteria) this;
        }

        public Criteria andMergeRcodeLike(String value) {
            addCriterion("merge_rcode like", value, "mergeRcode");
            return (Criteria) this;
        }

        public Criteria andMergeRcodeNotLike(String value) {
            addCriterion("merge_rcode not like", value, "mergeRcode");
            return (Criteria) this;
        }

        public Criteria andMergeRcodeIn(List<String> values) {
            addCriterion("merge_rcode in", values, "mergeRcode");
            return (Criteria) this;
        }

        public Criteria andMergeRcodeNotIn(List<String> values) {
            addCriterion("merge_rcode not in", values, "mergeRcode");
            return (Criteria) this;
        }

        public Criteria andMergeRcodeBetween(String value1, String value2) {
            addCriterion("merge_rcode between", value1, value2, "mergeRcode");
            return (Criteria) this;
        }

        public Criteria andMergeRcodeNotBetween(String value1, String value2) {
            addCriterion("merge_rcode not between", value1, value2, "mergeRcode");
            return (Criteria) this;
        }

        public Criteria andRefuseRcodeIsNull() {
            addCriterion("refuse_rcode is null");
            return (Criteria) this;
        }

        public Criteria andRefuseRcodeIsNotNull() {
            addCriterion("refuse_rcode is not null");
            return (Criteria) this;
        }

        public Criteria andRefuseRcodeEqualTo(String value) {
            addCriterion("refuse_rcode =", value, "refuseRcode");
            return (Criteria) this;
        }

        public Criteria andRefuseRcodeNotEqualTo(String value) {
            addCriterion("refuse_rcode <>", value, "refuseRcode");
            return (Criteria) this;
        }

        public Criteria andRefuseRcodeGreaterThan(String value) {
            addCriterion("refuse_rcode >", value, "refuseRcode");
            return (Criteria) this;
        }

        public Criteria andRefuseRcodeGreaterThanOrEqualTo(String value) {
            addCriterion("refuse_rcode >=", value, "refuseRcode");
            return (Criteria) this;
        }

        public Criteria andRefuseRcodeLessThan(String value) {
            addCriterion("refuse_rcode <", value, "refuseRcode");
            return (Criteria) this;
        }

        public Criteria andRefuseRcodeLessThanOrEqualTo(String value) {
            addCriterion("refuse_rcode <=", value, "refuseRcode");
            return (Criteria) this;
        }

        public Criteria andRefuseRcodeLike(String value) {
            addCriterion("refuse_rcode like", value, "refuseRcode");
            return (Criteria) this;
        }

        public Criteria andRefuseRcodeNotLike(String value) {
            addCriterion("refuse_rcode not like", value, "refuseRcode");
            return (Criteria) this;
        }

        public Criteria andRefuseRcodeIn(List<String> values) {
            addCriterion("refuse_rcode in", values, "refuseRcode");
            return (Criteria) this;
        }

        public Criteria andRefuseRcodeNotIn(List<String> values) {
            addCriterion("refuse_rcode not in", values, "refuseRcode");
            return (Criteria) this;
        }

        public Criteria andRefuseRcodeBetween(String value1, String value2) {
            addCriterion("refuse_rcode between", value1, value2, "refuseRcode");
            return (Criteria) this;
        }

        public Criteria andRefuseRcodeNotBetween(String value1, String value2) {
            addCriterion("refuse_rcode not between", value1, value2, "refuseRcode");
            return (Criteria) this;
        }

        public Criteria andRiskNodeIsNull() {
            addCriterion("risk_node is null");
            return (Criteria) this;
        }

        public Criteria andRiskNodeIsNotNull() {
            addCriterion("risk_node is not null");
            return (Criteria) this;
        }

        public Criteria andRiskNodeEqualTo(String value) {
            addCriterion("risk_node =", value, "riskNode");
            return (Criteria) this;
        }

        public Criteria andRiskNodeNotEqualTo(String value) {
            addCriterion("risk_node <>", value, "riskNode");
            return (Criteria) this;
        }

        public Criteria andRiskNodeGreaterThan(String value) {
            addCriterion("risk_node >", value, "riskNode");
            return (Criteria) this;
        }

        public Criteria andRiskNodeGreaterThanOrEqualTo(String value) {
            addCriterion("risk_node >=", value, "riskNode");
            return (Criteria) this;
        }

        public Criteria andRiskNodeLessThan(String value) {
            addCriterion("risk_node <", value, "riskNode");
            return (Criteria) this;
        }

        public Criteria andRiskNodeLessThanOrEqualTo(String value) {
            addCriterion("risk_node <=", value, "riskNode");
            return (Criteria) this;
        }

        public Criteria andRiskNodeLike(String value) {
            addCriterion("risk_node like", value, "riskNode");
            return (Criteria) this;
        }

        public Criteria andRiskNodeNotLike(String value) {
            addCriterion("risk_node not like", value, "riskNode");
            return (Criteria) this;
        }

        public Criteria andRiskNodeIn(List<String> values) {
            addCriterion("risk_node in", values, "riskNode");
            return (Criteria) this;
        }

        public Criteria andRiskNodeNotIn(List<String> values) {
            addCriterion("risk_node not in", values, "riskNode");
            return (Criteria) this;
        }

        public Criteria andRiskNodeBetween(String value1, String value2) {
            addCriterion("risk_node between", value1, value2, "riskNode");
            return (Criteria) this;
        }

        public Criteria andRiskNodeNotBetween(String value1, String value2) {
            addCriterion("risk_node not between", value1, value2, "riskNode");
            return (Criteria) this;
        }

        public Criteria andTreeGroupIsNull() {
            addCriterion("tree_group is null");
            return (Criteria) this;
        }

        public Criteria andTreeGroupIsNotNull() {
            addCriterion("tree_group is not null");
            return (Criteria) this;
        }

        public Criteria andTreeGroupEqualTo(String value) {
            addCriterion("tree_group =", value, "treeGroup");
            return (Criteria) this;
        }

        public Criteria andTreeGroupNotEqualTo(String value) {
            addCriterion("tree_group <>", value, "treeGroup");
            return (Criteria) this;
        }

        public Criteria andTreeGroupGreaterThan(String value) {
            addCriterion("tree_group >", value, "treeGroup");
            return (Criteria) this;
        }

        public Criteria andTreeGroupGreaterThanOrEqualTo(String value) {
            addCriterion("tree_group >=", value, "treeGroup");
            return (Criteria) this;
        }

        public Criteria andTreeGroupLessThan(String value) {
            addCriterion("tree_group <", value, "treeGroup");
            return (Criteria) this;
        }

        public Criteria andTreeGroupLessThanOrEqualTo(String value) {
            addCriterion("tree_group <=", value, "treeGroup");
            return (Criteria) this;
        }

        public Criteria andTreeGroupLike(String value) {
            addCriterion("tree_group like", value, "treeGroup");
            return (Criteria) this;
        }

        public Criteria andTreeGroupNotLike(String value) {
            addCriterion("tree_group not like", value, "treeGroup");
            return (Criteria) this;
        }

        public Criteria andTreeGroupIn(List<String> values) {
            addCriterion("tree_group in", values, "treeGroup");
            return (Criteria) this;
        }

        public Criteria andTreeGroupNotIn(List<String> values) {
            addCriterion("tree_group not in", values, "treeGroup");
            return (Criteria) this;
        }

        public Criteria andTreeGroupBetween(String value1, String value2) {
            addCriterion("tree_group between", value1, value2, "treeGroup");
            return (Criteria) this;
        }

        public Criteria andTreeGroupNotBetween(String value1, String value2) {
            addCriterion("tree_group not between", value1, value2, "treeGroup");
            return (Criteria) this;
        }

        public Criteria andFundRcodeIsNull() {
            addCriterion("fund_rcode is null");
            return (Criteria) this;
        }

        public Criteria andFundRcodeIsNotNull() {
            addCriterion("fund_rcode is not null");
            return (Criteria) this;
        }

        public Criteria andFundRcodeEqualTo(String value) {
            addCriterion("fund_rcode =", value, "fundRcode");
            return (Criteria) this;
        }

        public Criteria andFundRcodeNotEqualTo(String value) {
            addCriterion("fund_rcode <>", value, "fundRcode");
            return (Criteria) this;
        }

        public Criteria andFundRcodeGreaterThan(String value) {
            addCriterion("fund_rcode >", value, "fundRcode");
            return (Criteria) this;
        }

        public Criteria andFundRcodeGreaterThanOrEqualTo(String value) {
            addCriterion("fund_rcode >=", value, "fundRcode");
            return (Criteria) this;
        }

        public Criteria andFundRcodeLessThan(String value) {
            addCriterion("fund_rcode <", value, "fundRcode");
            return (Criteria) this;
        }

        public Criteria andFundRcodeLessThanOrEqualTo(String value) {
            addCriterion("fund_rcode <=", value, "fundRcode");
            return (Criteria) this;
        }

        public Criteria andFundRcodeLike(String value) {
            addCriterion("fund_rcode like", value, "fundRcode");
            return (Criteria) this;
        }

        public Criteria andFundRcodeNotLike(String value) {
            addCriterion("fund_rcode not like", value, "fundRcode");
            return (Criteria) this;
        }

        public Criteria andFundRcodeIn(List<String> values) {
            addCriterion("fund_rcode in", values, "fundRcode");
            return (Criteria) this;
        }

        public Criteria andFundRcodeNotIn(List<String> values) {
            addCriterion("fund_rcode not in", values, "fundRcode");
            return (Criteria) this;
        }

        public Criteria andFundRcodeBetween(String value1, String value2) {
            addCriterion("fund_rcode between", value1, value2, "fundRcode");
            return (Criteria) this;
        }

        public Criteria andFundRcodeNotBetween(String value1, String value2) {
            addCriterion("fund_rcode not between", value1, value2, "fundRcode");
            return (Criteria) this;
        }

        public Criteria andBlacklistRcodeIsNull() {
            addCriterion("blacklist_rcode is null");
            return (Criteria) this;
        }

        public Criteria andBlacklistRcodeIsNotNull() {
            addCriterion("blacklist_rcode is not null");
            return (Criteria) this;
        }

        public Criteria andBlacklistRcodeEqualTo(String value) {
            addCriterion("blacklist_rcode =", value, "blacklistRcode");
            return (Criteria) this;
        }

        public Criteria andBlacklistRcodeNotEqualTo(String value) {
            addCriterion("blacklist_rcode <>", value, "blacklistRcode");
            return (Criteria) this;
        }

        public Criteria andBlacklistRcodeGreaterThan(String value) {
            addCriterion("blacklist_rcode >", value, "blacklistRcode");
            return (Criteria) this;
        }

        public Criteria andBlacklistRcodeGreaterThanOrEqualTo(String value) {
            addCriterion("blacklist_rcode >=", value, "blacklistRcode");
            return (Criteria) this;
        }

        public Criteria andBlacklistRcodeLessThan(String value) {
            addCriterion("blacklist_rcode <", value, "blacklistRcode");
            return (Criteria) this;
        }

        public Criteria andBlacklistRcodeLessThanOrEqualTo(String value) {
            addCriterion("blacklist_rcode <=", value, "blacklistRcode");
            return (Criteria) this;
        }

        public Criteria andBlacklistRcodeLike(String value) {
            addCriterion("blacklist_rcode like", value, "blacklistRcode");
            return (Criteria) this;
        }

        public Criteria andBlacklistRcodeNotLike(String value) {
            addCriterion("blacklist_rcode not like", value, "blacklistRcode");
            return (Criteria) this;
        }

        public Criteria andBlacklistRcodeIn(List<String> values) {
            addCriterion("blacklist_rcode in", values, "blacklistRcode");
            return (Criteria) this;
        }

        public Criteria andBlacklistRcodeNotIn(List<String> values) {
            addCriterion("blacklist_rcode not in", values, "blacklistRcode");
            return (Criteria) this;
        }

        public Criteria andBlacklistRcodeBetween(String value1, String value2) {
            addCriterion("blacklist_rcode between", value1, value2, "blacklistRcode");
            return (Criteria) this;
        }

        public Criteria andBlacklistRcodeNotBetween(String value1, String value2) {
            addCriterion("blacklist_rcode not between", value1, value2, "blacklistRcode");
            return (Criteria) this;
        }

        public Criteria andExternalRcodeIsNull() {
            addCriterion("external_rcode is null");
            return (Criteria) this;
        }

        public Criteria andExternalRcodeIsNotNull() {
            addCriterion("external_rcode is not null");
            return (Criteria) this;
        }

        public Criteria andExternalRcodeEqualTo(String value) {
            addCriterion("external_rcode =", value, "externalRcode");
            return (Criteria) this;
        }

        public Criteria andExternalRcodeNotEqualTo(String value) {
            addCriterion("external_rcode <>", value, "externalRcode");
            return (Criteria) this;
        }

        public Criteria andExternalRcodeGreaterThan(String value) {
            addCriterion("external_rcode >", value, "externalRcode");
            return (Criteria) this;
        }

        public Criteria andExternalRcodeGreaterThanOrEqualTo(String value) {
            addCriterion("external_rcode >=", value, "externalRcode");
            return (Criteria) this;
        }

        public Criteria andExternalRcodeLessThan(String value) {
            addCriterion("external_rcode <", value, "externalRcode");
            return (Criteria) this;
        }

        public Criteria andExternalRcodeLessThanOrEqualTo(String value) {
            addCriterion("external_rcode <=", value, "externalRcode");
            return (Criteria) this;
        }

        public Criteria andExternalRcodeLike(String value) {
            addCriterion("external_rcode like", value, "externalRcode");
            return (Criteria) this;
        }

        public Criteria andExternalRcodeNotLike(String value) {
            addCriterion("external_rcode not like", value, "externalRcode");
            return (Criteria) this;
        }

        public Criteria andExternalRcodeIn(List<String> values) {
            addCriterion("external_rcode in", values, "externalRcode");
            return (Criteria) this;
        }

        public Criteria andExternalRcodeNotIn(List<String> values) {
            addCriterion("external_rcode not in", values, "externalRcode");
            return (Criteria) this;
        }

        public Criteria andExternalRcodeBetween(String value1, String value2) {
            addCriterion("external_rcode between", value1, value2, "externalRcode");
            return (Criteria) this;
        }

        public Criteria andExternalRcodeNotBetween(String value1, String value2) {
            addCriterion("external_rcode not between", value1, value2, "externalRcode");
            return (Criteria) this;
        }

        public Criteria andQianhaiRcodeIsNull() {
            addCriterion("qianhai_rcode is null");
            return (Criteria) this;
        }

        public Criteria andQianhaiRcodeIsNotNull() {
            addCriterion("qianhai_rcode is not null");
            return (Criteria) this;
        }

        public Criteria andQianhaiRcodeEqualTo(String value) {
            addCriterion("qianhai_rcode =", value, "qianhaiRcode");
            return (Criteria) this;
        }

        public Criteria andQianhaiRcodeNotEqualTo(String value) {
            addCriterion("qianhai_rcode <>", value, "qianhaiRcode");
            return (Criteria) this;
        }

        public Criteria andQianhaiRcodeGreaterThan(String value) {
            addCriterion("qianhai_rcode >", value, "qianhaiRcode");
            return (Criteria) this;
        }

        public Criteria andQianhaiRcodeGreaterThanOrEqualTo(String value) {
            addCriterion("qianhai_rcode >=", value, "qianhaiRcode");
            return (Criteria) this;
        }

        public Criteria andQianhaiRcodeLessThan(String value) {
            addCriterion("qianhai_rcode <", value, "qianhaiRcode");
            return (Criteria) this;
        }

        public Criteria andQianhaiRcodeLessThanOrEqualTo(String value) {
            addCriterion("qianhai_rcode <=", value, "qianhaiRcode");
            return (Criteria) this;
        }

        public Criteria andQianhaiRcodeLike(String value) {
            addCriterion("qianhai_rcode like", value, "qianhaiRcode");
            return (Criteria) this;
        }

        public Criteria andQianhaiRcodeNotLike(String value) {
            addCriterion("qianhai_rcode not like", value, "qianhaiRcode");
            return (Criteria) this;
        }

        public Criteria andQianhaiRcodeIn(List<String> values) {
            addCriterion("qianhai_rcode in", values, "qianhaiRcode");
            return (Criteria) this;
        }

        public Criteria andQianhaiRcodeNotIn(List<String> values) {
            addCriterion("qianhai_rcode not in", values, "qianhaiRcode");
            return (Criteria) this;
        }

        public Criteria andQianhaiRcodeBetween(String value1, String value2) {
            addCriterion("qianhai_rcode between", value1, value2, "qianhaiRcode");
            return (Criteria) this;
        }

        public Criteria andQianhaiRcodeNotBetween(String value1, String value2) {
            addCriterion("qianhai_rcode not between", value1, value2, "qianhaiRcode");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andScoreIsNull() {
            addCriterion("score is null");
            return (Criteria) this;
        }

        public Criteria andScoreIsNotNull() {
            addCriterion("score is not null");
            return (Criteria) this;
        }

        public Criteria andScoreEqualTo(String value) {
            addCriterion("score =", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreNotEqualTo(String value) {
            addCriterion("score <>", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreGreaterThan(String value) {
            addCriterion("score >", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreGreaterThanOrEqualTo(String value) {
            addCriterion("score >=", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreLessThan(String value) {
            addCriterion("score <", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreLessThanOrEqualTo(String value) {
            addCriterion("score <=", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreLike(String value) {
            addCriterion("score like", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreNotLike(String value) {
            addCriterion("score not like", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreIn(List<String> values) {
            addCriterion("score in", values, "score");
            return (Criteria) this;
        }

        public Criteria andScoreNotIn(List<String> values) {
            addCriterion("score not in", values, "score");
            return (Criteria) this;
        }

        public Criteria andScoreBetween(String value1, String value2) {
            addCriterion("score between", value1, value2, "score");
            return (Criteria) this;
        }

        public Criteria andScoreNotBetween(String value1, String value2) {
            addCriterion("score not between", value1, value2, "score");
            return (Criteria) this;
        }

        public Criteria andTdBlacklistDetailIsNull() {
            addCriterion("td_blacklist_detail is null");
            return (Criteria) this;
        }

        public Criteria andTdBlacklistDetailIsNotNull() {
            addCriterion("td_blacklist_detail is not null");
            return (Criteria) this;
        }

        public Criteria andTdBlacklistDetailEqualTo(String value) {
            addCriterion("td_blacklist_detail =", value, "tdBlacklistDetail");
            return (Criteria) this;
        }

        public Criteria andTdBlacklistDetailNotEqualTo(String value) {
            addCriterion("td_blacklist_detail <>", value, "tdBlacklistDetail");
            return (Criteria) this;
        }

        public Criteria andTdBlacklistDetailGreaterThan(String value) {
            addCriterion("td_blacklist_detail >", value, "tdBlacklistDetail");
            return (Criteria) this;
        }

        public Criteria andTdBlacklistDetailGreaterThanOrEqualTo(String value) {
            addCriterion("td_blacklist_detail >=", value, "tdBlacklistDetail");
            return (Criteria) this;
        }

        public Criteria andTdBlacklistDetailLessThan(String value) {
            addCriterion("td_blacklist_detail <", value, "tdBlacklistDetail");
            return (Criteria) this;
        }

        public Criteria andTdBlacklistDetailLessThanOrEqualTo(String value) {
            addCriterion("td_blacklist_detail <=", value, "tdBlacklistDetail");
            return (Criteria) this;
        }

        public Criteria andTdBlacklistDetailLike(String value) {
            addCriterion("td_blacklist_detail like", value, "tdBlacklistDetail");
            return (Criteria) this;
        }

        public Criteria andTdBlacklistDetailNotLike(String value) {
            addCriterion("td_blacklist_detail not like", value, "tdBlacklistDetail");
            return (Criteria) this;
        }

        public Criteria andTdBlacklistDetailIn(List<String> values) {
            addCriterion("td_blacklist_detail in", values, "tdBlacklistDetail");
            return (Criteria) this;
        }

        public Criteria andTdBlacklistDetailNotIn(List<String> values) {
            addCriterion("td_blacklist_detail not in", values, "tdBlacklistDetail");
            return (Criteria) this;
        }

        public Criteria andTdBlacklistDetailBetween(String value1, String value2) {
            addCriterion("td_blacklist_detail between", value1, value2, "tdBlacklistDetail");
            return (Criteria) this;
        }

        public Criteria andTdBlacklistDetailNotBetween(String value1, String value2) {
            addCriterion("td_blacklist_detail not between", value1, value2, "tdBlacklistDetail");
            return (Criteria) this;
        }

        public Criteria andBrBlacklistDetailIsNull() {
            addCriterion("br_blacklist_detail is null");
            return (Criteria) this;
        }

        public Criteria andBrBlacklistDetailIsNotNull() {
            addCriterion("br_blacklist_detail is not null");
            return (Criteria) this;
        }

        public Criteria andBrBlacklistDetailEqualTo(String value) {
            addCriterion("br_blacklist_detail =", value, "brBlacklistDetail");
            return (Criteria) this;
        }

        public Criteria andBrBlacklistDetailNotEqualTo(String value) {
            addCriterion("br_blacklist_detail <>", value, "brBlacklistDetail");
            return (Criteria) this;
        }

        public Criteria andBrBlacklistDetailGreaterThan(String value) {
            addCriterion("br_blacklist_detail >", value, "brBlacklistDetail");
            return (Criteria) this;
        }

        public Criteria andBrBlacklistDetailGreaterThanOrEqualTo(String value) {
            addCriterion("br_blacklist_detail >=", value, "brBlacklistDetail");
            return (Criteria) this;
        }

        public Criteria andBrBlacklistDetailLessThan(String value) {
            addCriterion("br_blacklist_detail <", value, "brBlacklistDetail");
            return (Criteria) this;
        }

        public Criteria andBrBlacklistDetailLessThanOrEqualTo(String value) {
            addCriterion("br_blacklist_detail <=", value, "brBlacklistDetail");
            return (Criteria) this;
        }

        public Criteria andBrBlacklistDetailLike(String value) {
            addCriterion("br_blacklist_detail like", value, "brBlacklistDetail");
            return (Criteria) this;
        }

        public Criteria andBrBlacklistDetailNotLike(String value) {
            addCriterion("br_blacklist_detail not like", value, "brBlacklistDetail");
            return (Criteria) this;
        }

        public Criteria andBrBlacklistDetailIn(List<String> values) {
            addCriterion("br_blacklist_detail in", values, "brBlacklistDetail");
            return (Criteria) this;
        }

        public Criteria andBrBlacklistDetailNotIn(List<String> values) {
            addCriterion("br_blacklist_detail not in", values, "brBlacklistDetail");
            return (Criteria) this;
        }

        public Criteria andBrBlacklistDetailBetween(String value1, String value2) {
            addCriterion("br_blacklist_detail between", value1, value2, "brBlacklistDetail");
            return (Criteria) this;
        }

        public Criteria andBrBlacklistDetailNotBetween(String value1, String value2) {
            addCriterion("br_blacklist_detail not between", value1, value2, "brBlacklistDetail");
            return (Criteria) this;
        }

        public Criteria andLwDriverStatusIsNull() {
            addCriterion("lw_driver_status is null");
            return (Criteria) this;
        }

        public Criteria andLwDriverStatusIsNotNull() {
            addCriterion("lw_driver_status is not null");
            return (Criteria) this;
        }

        public Criteria andLwDriverStatusEqualTo(String value) {
            addCriterion("lw_driver_status =", value, "lwDriverStatus");
            return (Criteria) this;
        }

        public Criteria andLwDriverStatusNotEqualTo(String value) {
            addCriterion("lw_driver_status <>", value, "lwDriverStatus");
            return (Criteria) this;
        }

        public Criteria andLwDriverStatusGreaterThan(String value) {
            addCriterion("lw_driver_status >", value, "lwDriverStatus");
            return (Criteria) this;
        }

        public Criteria andLwDriverStatusGreaterThanOrEqualTo(String value) {
            addCriterion("lw_driver_status >=", value, "lwDriverStatus");
            return (Criteria) this;
        }

        public Criteria andLwDriverStatusLessThan(String value) {
            addCriterion("lw_driver_status <", value, "lwDriverStatus");
            return (Criteria) this;
        }

        public Criteria andLwDriverStatusLessThanOrEqualTo(String value) {
            addCriterion("lw_driver_status <=", value, "lwDriverStatus");
            return (Criteria) this;
        }

        public Criteria andLwDriverStatusLike(String value) {
            addCriterion("lw_driver_status like", value, "lwDriverStatus");
            return (Criteria) this;
        }

        public Criteria andLwDriverStatusNotLike(String value) {
            addCriterion("lw_driver_status not like", value, "lwDriverStatus");
            return (Criteria) this;
        }

        public Criteria andLwDriverStatusIn(List<String> values) {
            addCriterion("lw_driver_status in", values, "lwDriverStatus");
            return (Criteria) this;
        }

        public Criteria andLwDriverStatusNotIn(List<String> values) {
            addCriterion("lw_driver_status not in", values, "lwDriverStatus");
            return (Criteria) this;
        }

        public Criteria andLwDriverStatusBetween(String value1, String value2) {
            addCriterion("lw_driver_status between", value1, value2, "lwDriverStatus");
            return (Criteria) this;
        }

        public Criteria andLwDriverStatusNotBetween(String value1, String value2) {
            addCriterion("lw_driver_status not between", value1, value2, "lwDriverStatus");
            return (Criteria) this;
        }

        public Criteria andQhCredooScoreIsNull() {
            addCriterion("qh_credoo_score is null");
            return (Criteria) this;
        }

        public Criteria andQhCredooScoreIsNotNull() {
            addCriterion("qh_credoo_score is not null");
            return (Criteria) this;
        }

        public Criteria andQhCredooScoreEqualTo(Integer value) {
            addCriterion("qh_credoo_score =", value, "qhCredooScore");
            return (Criteria) this;
        }

        public Criteria andQhCredooScoreNotEqualTo(Integer value) {
            addCriterion("qh_credoo_score <>", value, "qhCredooScore");
            return (Criteria) this;
        }

        public Criteria andQhCredooScoreGreaterThan(Integer value) {
            addCriterion("qh_credoo_score >", value, "qhCredooScore");
            return (Criteria) this;
        }

        public Criteria andQhCredooScoreGreaterThanOrEqualTo(Integer value) {
            addCriterion("qh_credoo_score >=", value, "qhCredooScore");
            return (Criteria) this;
        }

        public Criteria andQhCredooScoreLessThan(Integer value) {
            addCriterion("qh_credoo_score <", value, "qhCredooScore");
            return (Criteria) this;
        }

        public Criteria andQhCredooScoreLessThanOrEqualTo(Integer value) {
            addCriterion("qh_credoo_score <=", value, "qhCredooScore");
            return (Criteria) this;
        }

        public Criteria andQhCredooScoreIn(List<Integer> values) {
            addCriterion("qh_credoo_score in", values, "qhCredooScore");
            return (Criteria) this;
        }

        public Criteria andQhCredooScoreNotIn(List<Integer> values) {
            addCriterion("qh_credoo_score not in", values, "qhCredooScore");
            return (Criteria) this;
        }

        public Criteria andQhCredooScoreBetween(Integer value1, Integer value2) {
            addCriterion("qh_credoo_score between", value1, value2, "qhCredooScore");
            return (Criteria) this;
        }

        public Criteria andQhCredooScoreNotBetween(Integer value1, Integer value2) {
            addCriterion("qh_credoo_score not between", value1, value2, "qhCredooScore");
            return (Criteria) this;
        }

        public Criteria andXlDataStatusValueIsNull() {
            addCriterion("xl_data_status_value is null");
            return (Criteria) this;
        }

        public Criteria andXlDataStatusValueIsNotNull() {
            addCriterion("xl_data_status_value is not null");
            return (Criteria) this;
        }

        public Criteria andXlDataStatusValueEqualTo(String value) {
            addCriterion("xl_data_status_value =", value, "xlDataStatusValue");
            return (Criteria) this;
        }

        public Criteria andXlDataStatusValueNotEqualTo(String value) {
            addCriterion("xl_data_status_value <>", value, "xlDataStatusValue");
            return (Criteria) this;
        }

        public Criteria andXlDataStatusValueGreaterThan(String value) {
            addCriterion("xl_data_status_value >", value, "xlDataStatusValue");
            return (Criteria) this;
        }

        public Criteria andXlDataStatusValueGreaterThanOrEqualTo(String value) {
            addCriterion("xl_data_status_value >=", value, "xlDataStatusValue");
            return (Criteria) this;
        }

        public Criteria andXlDataStatusValueLessThan(String value) {
            addCriterion("xl_data_status_value <", value, "xlDataStatusValue");
            return (Criteria) this;
        }

        public Criteria andXlDataStatusValueLessThanOrEqualTo(String value) {
            addCriterion("xl_data_status_value <=", value, "xlDataStatusValue");
            return (Criteria) this;
        }

        public Criteria andXlDataStatusValueLike(String value) {
            addCriterion("xl_data_status_value like", value, "xlDataStatusValue");
            return (Criteria) this;
        }

        public Criteria andXlDataStatusValueNotLike(String value) {
            addCriterion("xl_data_status_value not like", value, "xlDataStatusValue");
            return (Criteria) this;
        }

        public Criteria andXlDataStatusValueIn(List<String> values) {
            addCriterion("xl_data_status_value in", values, "xlDataStatusValue");
            return (Criteria) this;
        }

        public Criteria andXlDataStatusValueNotIn(List<String> values) {
            addCriterion("xl_data_status_value not in", values, "xlDataStatusValue");
            return (Criteria) this;
        }

        public Criteria andXlDataStatusValueBetween(String value1, String value2) {
            addCriterion("xl_data_status_value between", value1, value2, "xlDataStatusValue");
            return (Criteria) this;
        }

        public Criteria andXlDataStatusValueNotBetween(String value1, String value2) {
            addCriterion("xl_data_status_value not between", value1, value2, "xlDataStatusValue");
            return (Criteria) this;
        }

        public Criteria andInsRuleACodeIsNull() {
            addCriterion("ins_rule_a_code is null");
            return (Criteria) this;
        }

        public Criteria andInsRuleACodeIsNotNull() {
            addCriterion("ins_rule_a_code is not null");
            return (Criteria) this;
        }

        public Criteria andInsRuleACodeEqualTo(String value) {
            addCriterion("ins_rule_a_code =", value, "insRuleACode");
            return (Criteria) this;
        }

        public Criteria andInsRuleACodeNotEqualTo(String value) {
            addCriterion("ins_rule_a_code <>", value, "insRuleACode");
            return (Criteria) this;
        }

        public Criteria andInsRuleACodeGreaterThan(String value) {
            addCriterion("ins_rule_a_code >", value, "insRuleACode");
            return (Criteria) this;
        }

        public Criteria andInsRuleACodeGreaterThanOrEqualTo(String value) {
            addCriterion("ins_rule_a_code >=", value, "insRuleACode");
            return (Criteria) this;
        }

        public Criteria andInsRuleACodeLessThan(String value) {
            addCriterion("ins_rule_a_code <", value, "insRuleACode");
            return (Criteria) this;
        }

        public Criteria andInsRuleACodeLessThanOrEqualTo(String value) {
            addCriterion("ins_rule_a_code <=", value, "insRuleACode");
            return (Criteria) this;
        }

        public Criteria andInsRuleACodeLike(String value) {
            addCriterion("ins_rule_a_code like", value, "insRuleACode");
            return (Criteria) this;
        }

        public Criteria andInsRuleACodeNotLike(String value) {
            addCriterion("ins_rule_a_code not like", value, "insRuleACode");
            return (Criteria) this;
        }

        public Criteria andInsRuleACodeIn(List<String> values) {
            addCriterion("ins_rule_a_code in", values, "insRuleACode");
            return (Criteria) this;
        }

        public Criteria andInsRuleACodeNotIn(List<String> values) {
            addCriterion("ins_rule_a_code not in", values, "insRuleACode");
            return (Criteria) this;
        }

        public Criteria andInsRuleACodeBetween(String value1, String value2) {
            addCriterion("ins_rule_a_code between", value1, value2, "insRuleACode");
            return (Criteria) this;
        }

        public Criteria andInsRuleACodeNotBetween(String value1, String value2) {
            addCriterion("ins_rule_a_code not between", value1, value2, "insRuleACode");
            return (Criteria) this;
        }

        public Criteria andInsRuleBCodeIsNull() {
            addCriterion("ins_rule_b_code is null");
            return (Criteria) this;
        }

        public Criteria andInsRuleBCodeIsNotNull() {
            addCriterion("ins_rule_b_code is not null");
            return (Criteria) this;
        }

        public Criteria andInsRuleBCodeEqualTo(String value) {
            addCriterion("ins_rule_b_code =", value, "insRuleBCode");
            return (Criteria) this;
        }

        public Criteria andInsRuleBCodeNotEqualTo(String value) {
            addCriterion("ins_rule_b_code <>", value, "insRuleBCode");
            return (Criteria) this;
        }

        public Criteria andInsRuleBCodeGreaterThan(String value) {
            addCriterion("ins_rule_b_code >", value, "insRuleBCode");
            return (Criteria) this;
        }

        public Criteria andInsRuleBCodeGreaterThanOrEqualTo(String value) {
            addCriterion("ins_rule_b_code >=", value, "insRuleBCode");
            return (Criteria) this;
        }

        public Criteria andInsRuleBCodeLessThan(String value) {
            addCriterion("ins_rule_b_code <", value, "insRuleBCode");
            return (Criteria) this;
        }

        public Criteria andInsRuleBCodeLessThanOrEqualTo(String value) {
            addCriterion("ins_rule_b_code <=", value, "insRuleBCode");
            return (Criteria) this;
        }

        public Criteria andInsRuleBCodeLike(String value) {
            addCriterion("ins_rule_b_code like", value, "insRuleBCode");
            return (Criteria) this;
        }

        public Criteria andInsRuleBCodeNotLike(String value) {
            addCriterion("ins_rule_b_code not like", value, "insRuleBCode");
            return (Criteria) this;
        }

        public Criteria andInsRuleBCodeIn(List<String> values) {
            addCriterion("ins_rule_b_code in", values, "insRuleBCode");
            return (Criteria) this;
        }

        public Criteria andInsRuleBCodeNotIn(List<String> values) {
            addCriterion("ins_rule_b_code not in", values, "insRuleBCode");
            return (Criteria) this;
        }

        public Criteria andInsRuleBCodeBetween(String value1, String value2) {
            addCriterion("ins_rule_b_code between", value1, value2, "insRuleBCode");
            return (Criteria) this;
        }

        public Criteria andInsRuleBCodeNotBetween(String value1, String value2) {
            addCriterion("ins_rule_b_code not between", value1, value2, "insRuleBCode");
            return (Criteria) this;
        }

        public Criteria andRiskGradeIsNull() {
            addCriterion("risk_grade is null");
            return (Criteria) this;
        }

        public Criteria andRiskGradeIsNotNull() {
            addCriterion("risk_grade is not null");
            return (Criteria) this;
        }

        public Criteria andRiskGradeEqualTo(String value) {
            addCriterion("risk_grade =", value, "riskGrade");
            return (Criteria) this;
        }

        public Criteria andRiskGradeNotEqualTo(String value) {
            addCriterion("risk_grade <>", value, "riskGrade");
            return (Criteria) this;
        }

        public Criteria andRiskGradeGreaterThan(String value) {
            addCriterion("risk_grade >", value, "riskGrade");
            return (Criteria) this;
        }

        public Criteria andRiskGradeGreaterThanOrEqualTo(String value) {
            addCriterion("risk_grade >=", value, "riskGrade");
            return (Criteria) this;
        }

        public Criteria andRiskGradeLessThan(String value) {
            addCriterion("risk_grade <", value, "riskGrade");
            return (Criteria) this;
        }

        public Criteria andRiskGradeLessThanOrEqualTo(String value) {
            addCriterion("risk_grade <=", value, "riskGrade");
            return (Criteria) this;
        }

        public Criteria andRiskGradeLike(String value) {
            addCriterion("risk_grade like", value, "riskGrade");
            return (Criteria) this;
        }

        public Criteria andRiskGradeNotLike(String value) {
            addCriterion("risk_grade not like", value, "riskGrade");
            return (Criteria) this;
        }

        public Criteria andRiskGradeIn(List<String> values) {
            addCriterion("risk_grade in", values, "riskGrade");
            return (Criteria) this;
        }

        public Criteria andRiskGradeNotIn(List<String> values) {
            addCriterion("risk_grade not in", values, "riskGrade");
            return (Criteria) this;
        }

        public Criteria andRiskGradeBetween(String value1, String value2) {
            addCriterion("risk_grade between", value1, value2, "riskGrade");
            return (Criteria) this;
        }

        public Criteria andRiskGradeNotBetween(String value1, String value2) {
            addCriterion("risk_grade not between", value1, value2, "riskGrade");
            return (Criteria) this;
        }

        public Criteria andRiskLabelIsNull() {
            addCriterion("risk_label is null");
            return (Criteria) this;
        }

        public Criteria andRiskLabelIsNotNull() {
            addCriterion("risk_label is not null");
            return (Criteria) this;
        }

        public Criteria andRiskLabelEqualTo(String value) {
            addCriterion("risk_label =", value, "riskLabel");
            return (Criteria) this;
        }

        public Criteria andRiskLabelNotEqualTo(String value) {
            addCriterion("risk_label <>", value, "riskLabel");
            return (Criteria) this;
        }

        public Criteria andRiskLabelGreaterThan(String value) {
            addCriterion("risk_label >", value, "riskLabel");
            return (Criteria) this;
        }

        public Criteria andRiskLabelGreaterThanOrEqualTo(String value) {
            addCriterion("risk_label >=", value, "riskLabel");
            return (Criteria) this;
        }

        public Criteria andRiskLabelLessThan(String value) {
            addCriterion("risk_label <", value, "riskLabel");
            return (Criteria) this;
        }

        public Criteria andRiskLabelLessThanOrEqualTo(String value) {
            addCriterion("risk_label <=", value, "riskLabel");
            return (Criteria) this;
        }

        public Criteria andRiskLabelLike(String value) {
            addCriterion("risk_label like", value, "riskLabel");
            return (Criteria) this;
        }

        public Criteria andRiskLabelNotLike(String value) {
            addCriterion("risk_label not like", value, "riskLabel");
            return (Criteria) this;
        }

        public Criteria andRiskLabelIn(List<String> values) {
            addCriterion("risk_label in", values, "riskLabel");
            return (Criteria) this;
        }

        public Criteria andRiskLabelNotIn(List<String> values) {
            addCriterion("risk_label not in", values, "riskLabel");
            return (Criteria) this;
        }

        public Criteria andRiskLabelBetween(String value1, String value2) {
            addCriterion("risk_label between", value1, value2, "riskLabel");
            return (Criteria) this;
        }

        public Criteria andRiskLabelNotBetween(String value1, String value2) {
            addCriterion("risk_label not between", value1, value2, "riskLabel");
            return (Criteria) this;
        }

        public Criteria andWorkflowLabelIsNull() {
            addCriterion("workflow_label is null");
            return (Criteria) this;
        }

        public Criteria andWorkflowLabelIsNotNull() {
            addCriterion("workflow_label is not null");
            return (Criteria) this;
        }

        public Criteria andWorkflowLabelEqualTo(String value) {
            addCriterion("workflow_label =", value, "workflowLabel");
            return (Criteria) this;
        }

        public Criteria andWorkflowLabelNotEqualTo(String value) {
            addCriterion("workflow_label <>", value, "workflowLabel");
            return (Criteria) this;
        }

        public Criteria andWorkflowLabelGreaterThan(String value) {
            addCriterion("workflow_label >", value, "workflowLabel");
            return (Criteria) this;
        }

        public Criteria andWorkflowLabelGreaterThanOrEqualTo(String value) {
            addCriterion("workflow_label >=", value, "workflowLabel");
            return (Criteria) this;
        }

        public Criteria andWorkflowLabelLessThan(String value) {
            addCriterion("workflow_label <", value, "workflowLabel");
            return (Criteria) this;
        }

        public Criteria andWorkflowLabelLessThanOrEqualTo(String value) {
            addCriterion("workflow_label <=", value, "workflowLabel");
            return (Criteria) this;
        }

        public Criteria andWorkflowLabelLike(String value) {
            addCriterion("workflow_label like", value, "workflowLabel");
            return (Criteria) this;
        }

        public Criteria andWorkflowLabelNotLike(String value) {
            addCriterion("workflow_label not like", value, "workflowLabel");
            return (Criteria) this;
        }

        public Criteria andWorkflowLabelIn(List<String> values) {
            addCriterion("workflow_label in", values, "workflowLabel");
            return (Criteria) this;
        }

        public Criteria andWorkflowLabelNotIn(List<String> values) {
            addCriterion("workflow_label not in", values, "workflowLabel");
            return (Criteria) this;
        }

        public Criteria andWorkflowLabelBetween(String value1, String value2) {
            addCriterion("workflow_label between", value1, value2, "workflowLabel");
            return (Criteria) this;
        }

        public Criteria andWorkflowLabelNotBetween(String value1, String value2) {
            addCriterion("workflow_label not between", value1, value2, "workflowLabel");
            return (Criteria) this;
        }

        public Criteria andGztBadInfoDetailIsNull() {
            addCriterion("gzt_bad_info_detail is null");
            return (Criteria) this;
        }

        public Criteria andGztBadInfoDetailIsNotNull() {
            addCriterion("gzt_bad_info_detail is not null");
            return (Criteria) this;
        }

        public Criteria andGztBadInfoDetailEqualTo(String value) {
            addCriterion("gzt_bad_info_detail =", value, "gztBadInfoDetail");
            return (Criteria) this;
        }

        public Criteria andGztBadInfoDetailNotEqualTo(String value) {
            addCriterion("gzt_bad_info_detail <>", value, "gztBadInfoDetail");
            return (Criteria) this;
        }

        public Criteria andGztBadInfoDetailGreaterThan(String value) {
            addCriterion("gzt_bad_info_detail >", value, "gztBadInfoDetail");
            return (Criteria) this;
        }

        public Criteria andGztBadInfoDetailGreaterThanOrEqualTo(String value) {
            addCriterion("gzt_bad_info_detail >=", value, "gztBadInfoDetail");
            return (Criteria) this;
        }

        public Criteria andGztBadInfoDetailLessThan(String value) {
            addCriterion("gzt_bad_info_detail <", value, "gztBadInfoDetail");
            return (Criteria) this;
        }

        public Criteria andGztBadInfoDetailLessThanOrEqualTo(String value) {
            addCriterion("gzt_bad_info_detail <=", value, "gztBadInfoDetail");
            return (Criteria) this;
        }

        public Criteria andGztBadInfoDetailLike(String value) {
            addCriterion("gzt_bad_info_detail like", value, "gztBadInfoDetail");
            return (Criteria) this;
        }

        public Criteria andGztBadInfoDetailNotLike(String value) {
            addCriterion("gzt_bad_info_detail not like", value, "gztBadInfoDetail");
            return (Criteria) this;
        }

        public Criteria andGztBadInfoDetailIn(List<String> values) {
            addCriterion("gzt_bad_info_detail in", values, "gztBadInfoDetail");
            return (Criteria) this;
        }

        public Criteria andGztBadInfoDetailNotIn(List<String> values) {
            addCriterion("gzt_bad_info_detail not in", values, "gztBadInfoDetail");
            return (Criteria) this;
        }

        public Criteria andGztBadInfoDetailBetween(String value1, String value2) {
            addCriterion("gzt_bad_info_detail between", value1, value2, "gztBadInfoDetail");
            return (Criteria) this;
        }

        public Criteria andGztBadInfoDetailNotBetween(String value1, String value2) {
            addCriterion("gzt_bad_info_detail not between", value1, value2, "gztBadInfoDetail");
            return (Criteria) this;
        }

        public Criteria andMtGztBadInfoDetailIsNull() {
            addCriterion("mt_gzt_bad_info_detail is null");
            return (Criteria) this;
        }

        public Criteria andMtGztBadInfoDetailIsNotNull() {
            addCriterion("mt_gzt_bad_info_detail is not null");
            return (Criteria) this;
        }

        public Criteria andMtGztBadInfoDetailEqualTo(String value) {
            addCriterion("mt_gzt_bad_info_detail =", value, "mtGztBadInfoDetail");
            return (Criteria) this;
        }

        public Criteria andMtGztBadInfoDetailNotEqualTo(String value) {
            addCriterion("mt_gzt_bad_info_detail <>", value, "mtGztBadInfoDetail");
            return (Criteria) this;
        }

        public Criteria andMtGztBadInfoDetailGreaterThan(String value) {
            addCriterion("mt_gzt_bad_info_detail >", value, "mtGztBadInfoDetail");
            return (Criteria) this;
        }

        public Criteria andMtGztBadInfoDetailGreaterThanOrEqualTo(String value) {
            addCriterion("mt_gzt_bad_info_detail >=", value, "mtGztBadInfoDetail");
            return (Criteria) this;
        }

        public Criteria andMtGztBadInfoDetailLessThan(String value) {
            addCriterion("mt_gzt_bad_info_detail <", value, "mtGztBadInfoDetail");
            return (Criteria) this;
        }

        public Criteria andMtGztBadInfoDetailLessThanOrEqualTo(String value) {
            addCriterion("mt_gzt_bad_info_detail <=", value, "mtGztBadInfoDetail");
            return (Criteria) this;
        }

        public Criteria andMtGztBadInfoDetailLike(String value) {
            addCriterion("mt_gzt_bad_info_detail like", value, "mtGztBadInfoDetail");
            return (Criteria) this;
        }

        public Criteria andMtGztBadInfoDetailNotLike(String value) {
            addCriterion("mt_gzt_bad_info_detail not like", value, "mtGztBadInfoDetail");
            return (Criteria) this;
        }

        public Criteria andMtGztBadInfoDetailIn(List<String> values) {
            addCriterion("mt_gzt_bad_info_detail in", values, "mtGztBadInfoDetail");
            return (Criteria) this;
        }

        public Criteria andMtGztBadInfoDetailNotIn(List<String> values) {
            addCriterion("mt_gzt_bad_info_detail not in", values, "mtGztBadInfoDetail");
            return (Criteria) this;
        }

        public Criteria andMtGztBadInfoDetailBetween(String value1, String value2) {
            addCriterion("mt_gzt_bad_info_detail between", value1, value2, "mtGztBadInfoDetail");
            return (Criteria) this;
        }

        public Criteria andMtGztBadInfoDetailNotBetween(String value1, String value2) {
            addCriterion("mt_gzt_bad_info_detail not between", value1, value2, "mtGztBadInfoDetail");
            return (Criteria) this;
        }

        public Criteria andGtGztBadInfoDetailIsNull() {
            addCriterion("gt_gzt_bad_info_detail is null");
            return (Criteria) this;
        }

        public Criteria andGtGztBadInfoDetailIsNotNull() {
            addCriterion("gt_gzt_bad_info_detail is not null");
            return (Criteria) this;
        }

        public Criteria andGtGztBadInfoDetailEqualTo(String value) {
            addCriterion("gt_gzt_bad_info_detail =", value, "gtGztBadInfoDetail");
            return (Criteria) this;
        }

        public Criteria andGtGztBadInfoDetailNotEqualTo(String value) {
            addCriterion("gt_gzt_bad_info_detail <>", value, "gtGztBadInfoDetail");
            return (Criteria) this;
        }

        public Criteria andGtGztBadInfoDetailGreaterThan(String value) {
            addCriterion("gt_gzt_bad_info_detail >", value, "gtGztBadInfoDetail");
            return (Criteria) this;
        }

        public Criteria andGtGztBadInfoDetailGreaterThanOrEqualTo(String value) {
            addCriterion("gt_gzt_bad_info_detail >=", value, "gtGztBadInfoDetail");
            return (Criteria) this;
        }

        public Criteria andGtGztBadInfoDetailLessThan(String value) {
            addCriterion("gt_gzt_bad_info_detail <", value, "gtGztBadInfoDetail");
            return (Criteria) this;
        }

        public Criteria andGtGztBadInfoDetailLessThanOrEqualTo(String value) {
            addCriterion("gt_gzt_bad_info_detail <=", value, "gtGztBadInfoDetail");
            return (Criteria) this;
        }

        public Criteria andGtGztBadInfoDetailLike(String value) {
            addCriterion("gt_gzt_bad_info_detail like", value, "gtGztBadInfoDetail");
            return (Criteria) this;
        }

        public Criteria andGtGztBadInfoDetailNotLike(String value) {
            addCriterion("gt_gzt_bad_info_detail not like", value, "gtGztBadInfoDetail");
            return (Criteria) this;
        }

        public Criteria andGtGztBadInfoDetailIn(List<String> values) {
            addCriterion("gt_gzt_bad_info_detail in", values, "gtGztBadInfoDetail");
            return (Criteria) this;
        }

        public Criteria andGtGztBadInfoDetailNotIn(List<String> values) {
            addCriterion("gt_gzt_bad_info_detail not in", values, "gtGztBadInfoDetail");
            return (Criteria) this;
        }

        public Criteria andGtGztBadInfoDetailBetween(String value1, String value2) {
            addCriterion("gt_gzt_bad_info_detail between", value1, value2, "gtGztBadInfoDetail");
            return (Criteria) this;
        }

        public Criteria andGtGztBadInfoDetailNotBetween(String value1, String value2) {
            addCriterion("gt_gzt_bad_info_detail not between", value1, value2, "gtGztBadInfoDetail");
            return (Criteria) this;
        }

        public Criteria andPreCreditIsNull() {
            addCriterion("pre_credit is null");
            return (Criteria) this;
        }

        public Criteria andPreCreditIsNotNull() {
            addCriterion("pre_credit is not null");
            return (Criteria) this;
        }

        public Criteria andPreCreditEqualTo(Integer value) {
            addCriterion("pre_credit =", value, "preCredit");
            return (Criteria) this;
        }

        public Criteria andPreCreditNotEqualTo(Integer value) {
            addCriterion("pre_credit <>", value, "preCredit");
            return (Criteria) this;
        }

        public Criteria andPreCreditGreaterThan(Integer value) {
            addCriterion("pre_credit >", value, "preCredit");
            return (Criteria) this;
        }

        public Criteria andPreCreditGreaterThanOrEqualTo(Integer value) {
            addCriterion("pre_credit >=", value, "preCredit");
            return (Criteria) this;
        }

        public Criteria andPreCreditLessThan(Integer value) {
            addCriterion("pre_credit <", value, "preCredit");
            return (Criteria) this;
        }

        public Criteria andPreCreditLessThanOrEqualTo(Integer value) {
            addCriterion("pre_credit <=", value, "preCredit");
            return (Criteria) this;
        }

        public Criteria andPreCreditIn(List<Integer> values) {
            addCriterion("pre_credit in", values, "preCredit");
            return (Criteria) this;
        }

        public Criteria andPreCreditNotIn(List<Integer> values) {
            addCriterion("pre_credit not in", values, "preCredit");
            return (Criteria) this;
        }

        public Criteria andPreCreditBetween(Integer value1, Integer value2) {
            addCriterion("pre_credit between", value1, value2, "preCredit");
            return (Criteria) this;
        }

        public Criteria andPreCreditNotBetween(Integer value1, Integer value2) {
            addCriterion("pre_credit not between", value1, value2, "preCredit");
            return (Criteria) this;
        }

        public Criteria andPreRateIsNull() {
            addCriterion("pre_rate is null");
            return (Criteria) this;
        }

        public Criteria andPreRateIsNotNull() {
            addCriterion("pre_rate is not null");
            return (Criteria) this;
        }

        public Criteria andPreRateEqualTo(String value) {
            addCriterion("pre_rate =", value, "preRate");
            return (Criteria) this;
        }

        public Criteria andPreRateNotEqualTo(String value) {
            addCriterion("pre_rate <>", value, "preRate");
            return (Criteria) this;
        }

        public Criteria andPreRateGreaterThan(String value) {
            addCriterion("pre_rate >", value, "preRate");
            return (Criteria) this;
        }

        public Criteria andPreRateGreaterThanOrEqualTo(String value) {
            addCriterion("pre_rate >=", value, "preRate");
            return (Criteria) this;
        }

        public Criteria andPreRateLessThan(String value) {
            addCriterion("pre_rate <", value, "preRate");
            return (Criteria) this;
        }

        public Criteria andPreRateLessThanOrEqualTo(String value) {
            addCriterion("pre_rate <=", value, "preRate");
            return (Criteria) this;
        }

        public Criteria andPreRateLike(String value) {
            addCriterion("pre_rate like", value, "preRate");
            return (Criteria) this;
        }

        public Criteria andPreRateNotLike(String value) {
            addCriterion("pre_rate not like", value, "preRate");
            return (Criteria) this;
        }

        public Criteria andPreRateIn(List<String> values) {
            addCriterion("pre_rate in", values, "preRate");
            return (Criteria) this;
        }

        public Criteria andPreRateNotIn(List<String> values) {
            addCriterion("pre_rate not in", values, "preRate");
            return (Criteria) this;
        }

        public Criteria andPreRateBetween(String value1, String value2) {
            addCriterion("pre_rate between", value1, value2, "preRate");
            return (Criteria) this;
        }

        public Criteria andPreRateNotBetween(String value1, String value2) {
            addCriterion("pre_rate not between", value1, value2, "preRate");
            return (Criteria) this;
        }

        public Criteria andFraudAlertIsNull() {
            addCriterion("fraud_alert is null");
            return (Criteria) this;
        }

        public Criteria andFraudAlertIsNotNull() {
            addCriterion("fraud_alert is not null");
            return (Criteria) this;
        }

        public Criteria andFraudAlertEqualTo(String value) {
            addCriterion("fraud_alert =", value, "fraudAlert");
            return (Criteria) this;
        }

        public Criteria andFraudAlertNotEqualTo(String value) {
            addCriterion("fraud_alert <>", value, "fraudAlert");
            return (Criteria) this;
        }

        public Criteria andFraudAlertGreaterThan(String value) {
            addCriterion("fraud_alert >", value, "fraudAlert");
            return (Criteria) this;
        }

        public Criteria andFraudAlertGreaterThanOrEqualTo(String value) {
            addCriterion("fraud_alert >=", value, "fraudAlert");
            return (Criteria) this;
        }

        public Criteria andFraudAlertLessThan(String value) {
            addCriterion("fraud_alert <", value, "fraudAlert");
            return (Criteria) this;
        }

        public Criteria andFraudAlertLessThanOrEqualTo(String value) {
            addCriterion("fraud_alert <=", value, "fraudAlert");
            return (Criteria) this;
        }

        public Criteria andFraudAlertLike(String value) {
            addCriterion("fraud_alert like", value, "fraudAlert");
            return (Criteria) this;
        }

        public Criteria andFraudAlertNotLike(String value) {
            addCriterion("fraud_alert not like", value, "fraudAlert");
            return (Criteria) this;
        }

        public Criteria andFraudAlertIn(List<String> values) {
            addCriterion("fraud_alert in", values, "fraudAlert");
            return (Criteria) this;
        }

        public Criteria andFraudAlertNotIn(List<String> values) {
            addCriterion("fraud_alert not in", values, "fraudAlert");
            return (Criteria) this;
        }

        public Criteria andFraudAlertBetween(String value1, String value2) {
            addCriterion("fraud_alert between", value1, value2, "fraudAlert");
            return (Criteria) this;
        }

        public Criteria andFraudAlertNotBetween(String value1, String value2) {
            addCriterion("fraud_alert not between", value1, value2, "fraudAlert");
            return (Criteria) this;
        }

        public Criteria andFraudScoreIsNull() {
            addCriterion("fraud_score is null");
            return (Criteria) this;
        }

        public Criteria andFraudScoreIsNotNull() {
            addCriterion("fraud_score is not null");
            return (Criteria) this;
        }

        public Criteria andFraudScoreEqualTo(Integer value) {
            addCriterion("fraud_score =", value, "fraudScore");
            return (Criteria) this;
        }

        public Criteria andFraudScoreNotEqualTo(Integer value) {
            addCriterion("fraud_score <>", value, "fraudScore");
            return (Criteria) this;
        }

        public Criteria andFraudScoreGreaterThan(Integer value) {
            addCriterion("fraud_score >", value, "fraudScore");
            return (Criteria) this;
        }

        public Criteria andFraudScoreGreaterThanOrEqualTo(Integer value) {
            addCriterion("fraud_score >=", value, "fraudScore");
            return (Criteria) this;
        }

        public Criteria andFraudScoreLessThan(Integer value) {
            addCriterion("fraud_score <", value, "fraudScore");
            return (Criteria) this;
        }

        public Criteria andFraudScoreLessThanOrEqualTo(Integer value) {
            addCriterion("fraud_score <=", value, "fraudScore");
            return (Criteria) this;
        }

        public Criteria andFraudScoreIn(List<Integer> values) {
            addCriterion("fraud_score in", values, "fraudScore");
            return (Criteria) this;
        }

        public Criteria andFraudScoreNotIn(List<Integer> values) {
            addCriterion("fraud_score not in", values, "fraudScore");
            return (Criteria) this;
        }

        public Criteria andFraudScoreBetween(Integer value1, Integer value2) {
            addCriterion("fraud_score between", value1, value2, "fraudScore");
            return (Criteria) this;
        }

        public Criteria andFraudScoreNotBetween(Integer value1, Integer value2) {
            addCriterion("fraud_score not between", value1, value2, "fraudScore");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_ly_rule_result
     *
     * @mbggenerated do_not_delete_during_merge Mon Jun 12 16:25:49 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_ly_rule_result
     *
     * @mbggenerated Mon Jun 12 16:25:49 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}