package com.oo.test.dao.ly;

import com.oo.test.model.ly.LyRuleResult;
import com.oo.test.model.ly.LyRuleResultExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LyRuleResultMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ly_rule_result
     *
     * @mbggenerated Mon Jun 12 16:25:49 CST 2017
     */
    int countByExample(LyRuleResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ly_rule_result
     *
     * @mbggenerated Mon Jun 12 16:25:49 CST 2017
     */
    int deleteByExample(LyRuleResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ly_rule_result
     *
     * @mbggenerated Mon Jun 12 16:25:49 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ly_rule_result
     *
     * @mbggenerated Mon Jun 12 16:25:49 CST 2017
     */
    int insert(LyRuleResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ly_rule_result
     *
     * @mbggenerated Mon Jun 12 16:25:49 CST 2017
     */
    int insertSelective(LyRuleResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ly_rule_result
     *
     * @mbggenerated Mon Jun 12 16:25:49 CST 2017
     */
    List<LyRuleResult> selectByExampleWithBLOBs(LyRuleResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ly_rule_result
     *
     * @mbggenerated Mon Jun 12 16:25:49 CST 2017
     */
    List<LyRuleResult> selectByExample(LyRuleResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ly_rule_result
     *
     * @mbggenerated Mon Jun 12 16:25:49 CST 2017
     */
    LyRuleResult selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ly_rule_result
     *
     * @mbggenerated Mon Jun 12 16:25:49 CST 2017
     */
    int updateByExampleSelective(@Param("record") LyRuleResult record, @Param("example") LyRuleResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ly_rule_result
     *
     * @mbggenerated Mon Jun 12 16:25:49 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") LyRuleResult record, @Param("example") LyRuleResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ly_rule_result
     *
     * @mbggenerated Mon Jun 12 16:25:49 CST 2017
     */
    int updateByExample(@Param("record") LyRuleResult record, @Param("example") LyRuleResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ly_rule_result
     *
     * @mbggenerated Mon Jun 12 16:25:49 CST 2017
     */
    int updateByPrimaryKeySelective(LyRuleResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ly_rule_result
     *
     * @mbggenerated Mon Jun 12 16:25:49 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(LyRuleResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ly_rule_result
     *
     * @mbggenerated Mon Jun 12 16:25:49 CST 2017
     */
    int updateByPrimaryKey(LyRuleResult record);
}